[aws]
# format = 'on [$symbol($profile )(\($region\) )]($style)'
# style = 'bold blue'
# symbol = 'ğŸ…° '
force_display = true

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
[[battery.display]]
threshold = 60

# [env_var.on_vpn]
# variable = 'on_vpn'
# default = ''
# symbol = 'ğŸ¤“'

# [custom.vpn]
# command = 'custom_vpn_command_here' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$at_work" = "true" '''
# style = "bright-yellow bold"
# format = " at [$output]($style)"

[git_branch]
symbol = 'ğŸŒ± '
ignore_branches = ['master', 'main']

[kubernetes]
disabled = false
detect_files = ['ibex']

[memory_usage]
disabled = false

[shlvl]
disabled = false
threshold = 3

[sudo]
disabled = false
